import Link from 'next/link'
import '../globals.css'
import { getPages } from '@/sanity/sanity-utils';

export const metadata = {
  title: 'Article',
  description: 'Generated by Next + Sanity',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  //get all of our pages
  const pages = await getPages();


  return (
    <html lang="en">
      <body className="max-w-6xl mx-auto py-10">
        <header className='flex items-center justify-end'>
          {/* <Link href="/" className='bg-gradient-to-r from-orange-400 via-red-400 to-purple-600 bg-clip-text text-transparent text-5xl font-extrabold text-lg font-bold'>Chris</Link> */}
          <div className='flex items-center gap-5 text-sm text-gray-600'>
            <Link href={`/`} className='bg-gray-100 rounded-lg text-gray-500 font-bold py-3 px-4 whitespace-nowrap hover:bg-black hover:text-white transition'>
               Home
            </Link>
            {pages.map((page) => (
              <Link key={page._id} href={`/${page.slug}`} className='bg-gray-100 rounded-lg text-gray-500 font-bold py-3 px-4 whitespace-nowrap hover:bg-black hover:text-white transition'>
                {page.title}
              </Link>
            ))}
          </div>
        </header>
       <main className='py-20'>{children}</main>
      </body>
    </html>
  )
}
